fq:
  api:
    base-url: https://api5-normal-sinfonlineb.fqnovel.com
    cookie: store-region=cn-zj; store-region-src=did; install_id=670078579016233;
    device:
      aid: '1967'
      cdid: 5566b484-82f9-4cef-880d-60ca354e6a99
      device-brand: HUAWEI
      device-id: '670078578733609'
      device-type: WLZ-AN00
      dpi: '480'
      host-abi: arm64-v8a
      install-id: '670078579016233'
      resolution: 1920*1080
      rom-version: V433IR+release-keys
      update-version-code: '68132'
      version-code: '68132'
      version-name: 6.8.1.32
    user-agent: com.dragon.read.oversea.gp/68132 (Linux; U; Android 13; zh_CN; WLZ-AN00;
      Build/V433IR;tt-ok/3.12.13.4-tiktok)