server:
  port: 9999
  address: 0.0.0.0

application:
  unidbg:
    dynarmic: false
    verbose: false
    async: false

# FQ API 配置
fq:
    api:
        base-url: https://api5-normal-sinfonlineb.fqnovel.com
        user-agent: com.dragon.read.oversea.gp/68132 (Linux; U; Android 14; zh_CN; 2012123AC; Build/V451IR;tt-ok/3.12.13.4-tiktok)
        cookie: store-region=cn-zj; store-region-src=did; install_id=582117512755339;
        device:
          aid: '1967'
          cdid: a4dd2cc8-ec60-41f3-8601-57dc01f35a89
          device-brand: Xiaomi
          device-id: '582117512751243'
          device-type: 2012123AC
          dpi: '480'
          host-abi: arm64-v8a
          install-id: '582117512755339'
          resolution: 2400*1080
          rom-version: V451IR+release-keys
          update-version-code: '68132'
          version-code: '68132'
          version-name: 6.8.1.32


spring:
  application:
    name: unidbg-boot-server
  profiles:
    active: dev
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
  # Redis配置
  redis:
    host: 60.205.188.67
    port: 26586
    password: HT5aRYBK2HpReaQuYkLcg
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
