server:
  port: 9999
  address: 0.0.0.0
application:
  unidbg:
    dynarmic: false
    verbose: false
    async: false
fq:
  api:
    cookie: store-region=cn-zj; store-region-src=did; install_id=9573416740669858;
    device:
      host-abi: armeabi-v7a
      version-name: 6.8.1.32
      update-version-code: '68132'
      install-id: '9573416740669858'
      rom-version: V433IR+release-keys
      device-brand: Samsung
      device-id: '8799208778332873'
      resolution: 2560*1440
      cdid: af4773d4-ec1b-49bf-a87e-345a195a80c7
      device-type: GalaxyS23
      version-code: '68132'
      dpi: '560'
      aid: '1967'
    user-agent: com.dragon.read.oversea.gp/68132 (Linux; U; Android 13; zh_CN; GalaxyS23;
      Build/V433IR;tt-ok/3.12.13.4-tiktok)
spring:
  application:
    name: unidbg-boot-server
  profiles:
    active: dev
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        keep-alive: 60s
        max-size: 8
  redis:
    host: 60.205.188.67
    port: 26586
    password: HT5aRYBK2HpReaQuYkLcg
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
