package com.anjia.unidbgserver.service;

import com.anjia.unidbgserver.config.FQApiProperties;
import com.anjia.unidbgserver.dto.FqVariable;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

/**
 * 设备轮换服务
 * 每100次请求自动更换设备信息，支持多个设备信息轮换
 */
@Slf4j
@Service
public class DeviceRotationService {

    @Resource
    private FQApiProperties fqApiProperties;

    // 请求计数器
    private final AtomicLong requestCounter = new AtomicLong(0);
    
    // 轮换阈值（从配置读取）
    private long rotationThreshold = 100;
    
    // 设备信息池
    private final List<FQApiProperties.Device> devicePool = new ArrayList<>();
    
    // 当前使用的设备索引
    private volatile int currentDeviceIndex = 0;
    
    // 当前使用的FqVariable
    private volatile FqVariable currentFqVariable;
    
    // 设备信息持久化文件
    private static final String DEVICE_PERSISTENCE_FILE = "device_pool.json";
    private final ObjectMapper objectMapper = new ObjectMapper();
    
    // 用于生成设备ID的计数器
    private static int deviceIdCounter = 0;

    /**
     * 初始化设备池
     */
    @PostConstruct
    public void initializeDevicePool() {
        // 从配置读取轮换阈值
        if (fqApiProperties.getDeviceRotation() != null) {
            rotationThreshold = fqApiProperties.getDeviceRotation().getRotationThreshold();
        }
        
        // 检查是否启用设备轮换
        boolean enabled = fqApiProperties.getDeviceRotation() != null && 
                         fqApiProperties.getDeviceRotation().getEnabled();
        
        if (!enabled) {
            log.info("设备轮换功能已禁用");
            // 只添加默认设备配置
            devicePool.add(fqApiProperties.getDevice());
            updateCurrentDevice();
            return;
        }
        
        // 尝试从文件加载设备池
        if (loadDevicePoolFromFile()) {
            log.info("成功从文件加载设备池，设备数量: {}", devicePool.size());
        } else {
            log.info("无法从文件加载设备池，生成新的设备池");
            // 添加默认设备配置
            devicePool.add(fqApiProperties.getDevice());
            
            // 生成额外的设备配置
            boolean autoGenerate = fqApiProperties.getDeviceRotation() == null || 
                                  fqApiProperties.getDeviceRotation().getAutoGenerateDevices();
            if (autoGenerate) {
                generateAdditionalDevices();
            }
            
            // 保存设备池到文件
            saveDevicePoolToFile();
        }
        
        // 初始化当前设备
        updateCurrentDevice();
        
        log.info("设备轮换服务初始化完成，共加载 {} 个设备配置", devicePool.size());
        log.info("轮换阈值: 每 {} 次请求更换一次设备", rotationThreshold);
    }

    /**
     * 从文件加载设备池
     */
    private boolean loadDevicePoolFromFile() {
        try {
            File file = new File(DEVICE_PERSISTENCE_FILE);
            if (!file.exists()) {
                return false;
            }
            
            DevicePoolData data = objectMapper.readValue(file, DevicePoolData.class);
            devicePool.clear();
            devicePool.addAll(data.getDevices());
            currentDeviceIndex = data.getCurrentDeviceIndex();
            
            return true;
        } catch (IOException e) {
            log.warn("加载设备池文件失败: {}", e.getMessage());
            return false;
        }
    }
    
    /**
     * 保存设备池到文件
     */
    private void saveDevicePoolToFile() {
        try {
            DevicePoolData data = new DevicePoolData();
            data.setDevices(new ArrayList<>(devicePool));
            data.setCurrentDeviceIndex(currentDeviceIndex);
            data.setSaveTime(System.currentTimeMillis());
            
            objectMapper.writeValue(new File(DEVICE_PERSISTENCE_FILE), data);
            log.info("设备池已保存到文件: {}", DEVICE_PERSISTENCE_FILE);
        } catch (IOException e) {
            log.error("保存设备池文件失败: {}", e.getMessage());
        }
    }

    /**
     * 生成额外的设备配置
     */
    private void generateAdditionalDevices() {
        // 预定义一些设备配置
        String[][] deviceConfigs = {
            // Xiaomi设备
            {"Xiaomi", "24031PN0DC", "1600*900", "320", "arm64-v8a", "V417IR+release-keys"},
            {"Xiaomi", "RedmiK50", "2400*1080", "480", "arm64-v8a", "V433IR+release-keys"},
            {"Xiaomi", "MI13", "3200*1440", "640", "arm64-v8a", "V451IR+release-keys"},
            
            // HUAWEI设备
            {"HUAWEI", "nova9", "2560*1440", "560", "arm64-v8a", "V417IR+release-keys"},
            {"HUAWEI", "P50", "2340*1080", "440", "arm64-v8a", "V433IR+release-keys"},
            {"HUAWEI", "Mate50", "3200*1440", "640", "arm64-v8a", "V451IR+release-keys"},
            
            // OPPO设备
            {"OPPO", "FindX5", "2400*1080", "480", "arm64-v8a", "V417IR+release-keys"},
            {"OPPO", "Reno9", "2340*1080", "440", "arm64-v8a", "V433IR+release-keys"},
            
            // vivo设备
            {"vivo", "X80", "2400*1080", "480", "arm64-v8a", "V417IR+release-keys"},
            {"vivo", "S15", "2340*1080", "440", "arm64-v8a", "V433IR+release-keys"},
            
            // OnePlus设备
            {"OnePlus", "OnePlus11", "3200*1440", "640", "arm64-v8a", "V433IR+release-keys"},
            {"OnePlus", "OnePlus10", "2400*1080", "480", "arm64-v8a", "V417IR+release-keys"},
            
            // Samsung设备
            {"Samsung", "GalaxyS22", "3200*1440", "640", "arm64-v8a", "V433IR+release-keys"},
            {"Samsung", "GalaxyS23", "3200*1440", "640", "arm64-v8a", "V451IR+release-keys"}
        };

        for (String[] config : deviceConfigs) {
            FQApiProperties.Device device = new FQApiProperties.Device();
            device.setDeviceBrand(config[0]);
            device.setDeviceType(config[1]);
            device.setResolution(config[2]);
            device.setDpi(config[3]);
            device.setHostAbi(config[4]);
            device.setRomVersion(config[5]);
            
            // 生成唯一的设备标识符
            device.setCdid(generateUUID());
            device.setInstallId(generateDeviceId());
            device.setDeviceId(generateDeviceId());
            
            // 保持其他配置与默认设备一致
            device.setAid(fqApiProperties.getDevice().getAid());
            device.setVersionCode(fqApiProperties.getDevice().getVersionCode());
            device.setVersionName(fqApiProperties.getDevice().getVersionName());
            device.setUpdateVersionCode(fqApiProperties.getDevice().getUpdateVersionCode());
            
            devicePool.add(device);
        }
    }

    /**
     * 获取当前设备信息（自动轮换）
     */
    public FqVariable getCurrentDevice() {
        long currentCount = requestCounter.incrementAndGet();
        
        // 检查是否需要轮换设备
        if (currentCount % rotationThreshold == 0) {
            rotateDevice();
        }
        
        return currentFqVariable;
    }

    /**
     * 轮换到下一个设备
     */
    private synchronized void rotateDevice() {
        currentDeviceIndex = (currentDeviceIndex + 1) % devicePool.size();
        updateCurrentDevice();
        
        // 保存设备状态
        saveDevicePoolToFile();
        
        FQApiProperties.Device device = devicePool.get(currentDeviceIndex);
        log.info("设备轮换: 切换到设备 {} - {} {} (索引: {})", 
                currentDeviceIndex + 1, device.getDeviceBrand(), device.getDeviceType(), currentDeviceIndex);
    }

    /**
     * 更新当前设备
     */
    private void updateCurrentDevice() {
        FQApiProperties.Device device = devicePool.get(currentDeviceIndex);
        
        // 创建临时的FQApiProperties对象
        FQApiProperties tempProperties = new FQApiProperties();
        tempProperties.setDevice(device);
        
        // 创建新的FqVariable
        currentFqVariable = new FqVariable(tempProperties);
    }

    /**
     * 手动切换到指定设备
     */
    public synchronized void switchToDevice(int deviceIndex) {
        if (deviceIndex >= 0 && deviceIndex < devicePool.size()) {
            currentDeviceIndex = deviceIndex;
            updateCurrentDevice();
            
            FQApiProperties.Device device = devicePool.get(currentDeviceIndex);
            log.info("手动切换设备: {} - {} {}", 
                    deviceIndex + 1, device.getDeviceBrand(), device.getDeviceType());
        } else {
            log.warn("无效的设备索引: {}, 可用设备数量: {}", deviceIndex, devicePool.size());
        }
    }

    /**
     * 切换到下一个设备（用于失败重试）
     */
    public synchronized void switchToNextDevice() {
        rotateDevice();
    }

    /**
     * 获取设备池信息
     */
    public Map<String, Object> getDevicePoolInfo() {
        Map<String, Object> info = new HashMap<>();
        info.put("totalDevices", devicePool.size());
        info.put("currentDeviceIndex", currentDeviceIndex);
        info.put("rotationThreshold", rotationThreshold);
        info.put("requestCount", requestCounter.get());
        info.put("nextRotationAt", ((requestCounter.get() / rotationThreshold) + 1) * rotationThreshold);
        
        List<Map<String, Object>> devices = new ArrayList<>();
        for (int i = 0; i < devicePool.size(); i++) {
            FQApiProperties.Device device = devicePool.get(i);
            Map<String, Object> deviceInfo = new HashMap<>();
            deviceInfo.put("index", i);
            deviceInfo.put("brand", device.getDeviceBrand());
            deviceInfo.put("type", device.getDeviceType());
            deviceInfo.put("resolution", device.getResolution());
            deviceInfo.put("dpi", device.getDpi());
            deviceInfo.put("romVersion", device.getRomVersion());
            deviceInfo.put("deviceId", device.getDeviceId());
            deviceInfo.put("installId", device.getInstallId());
            deviceInfo.put("isCurrent", i == currentDeviceIndex);
            devices.add(deviceInfo);
        }
        info.put("devices", devices);
        
        return info;
    }

    /**
     * 重置请求计数器
     */
    public void resetRequestCounter() {
        requestCounter.set(0);
        log.info("请求计数器已重置");
    }

    /**
     * 生成UUID（使用固定种子确保一致性）
     */
    private String generateUUID() {
        // 使用固定种子生成UUID，确保重启后一致
        Random random = new Random(12345L + deviceIdCounter++);
        return UUID.randomUUID().toString();
    }

    /**
     * 生成设备ID（使用固定种子确保一致性）
     */
    private String generateDeviceId() {
        // 使用固定种子生成设备ID，确保重启后一致
        Random random = new Random(54321L + deviceIdCounter++);
        return String.valueOf(1000000000000000L + random.nextInt(900000000));
    }
    
    /**
     * 设备池数据类
     */
    public static class DevicePoolData {
        private List<FQApiProperties.Device> devices;
        private int currentDeviceIndex;
        private long saveTime;
        
        // Getters and Setters
        public List<FQApiProperties.Device> getDevices() { return devices; }
        public void setDevices(List<FQApiProperties.Device> devices) { this.devices = devices; }
        public int getCurrentDeviceIndex() { return currentDeviceIndex; }
        public void setCurrentDeviceIndex(int currentDeviceIndex) { this.currentDeviceIndex = currentDeviceIndex; }
        public long getSaveTime() { return saveTime; }
        public void setSaveTime(long saveTime) { this.saveTime = saveTime; }
    }
}
